/**
 * The app's tag taxonomy — kept intentionally small (18 tags) so every post
 * fits somewhere obvious. See docs/ or the Aug 2026 tag-consolidation pass
 * for the mapping this replaced (27 tags → 18).
 */
export enum TagCategory {
  Dating = 'dating',
  Game = 'game',
  Job = 'job', // legacy — kept for feed compatibility; no longer a business signup category
  Around = 'around',
  Shop = 'shop',
  Help = 'help',
  Food = 'food',
  Service = 'service',
  Beauty = 'beauty',
  Health = 'health',
  Fitness = 'fitness',
  Learn = 'learn',
  Auto = 'auto',
  Space = 'space',
  Travel = 'travel',
  Event = 'event',
  Notice = 'notice',
  Biz = 'biz',
  Alert = 'alert',
  Poll = 'poll',
  HotNow = 'hot-now',
}

export const TAG_COLORS: Readonly<Record<TagCategory, [string, string]>> = {
  [TagCategory.Dating]: ['#e11d48', '#be185d'],
  [TagCategory.Game]: ['#16a34a', '#0f766e'],
  [TagCategory.Job]: ['#2563eb', '#4338ca'],
  [TagCategory.Around]: ['#f59e0b', '#0d9488'],
  [TagCategory.Shop]: ['#f43f5e', '#be123c'],
  [TagCategory.Help]: ['#78716c', '#44403c'],
  [TagCategory.Food]: ['#f97316', '#c2410c'],
  [TagCategory.Service]: ['#64748b', '#475569'],
  [TagCategory.Beauty]: ['#ec4899', '#db2777'],
  [TagCategory.Health]: ['#84cc16', '#4d7c0f'],
  [TagCategory.Fitness]: ['#22c55e', '#15803d'],
  [TagCategory.Learn]: ['#0ea5e9', '#0369a1'],
  [TagCategory.Auto]: ['#f59e0b', '#d97706'],
  [TagCategory.Space]: ['#0891b2', '#155e75'],
  [TagCategory.Travel]: ['#fb923c', '#c2410c'],
  [TagCategory.Event]: ['#8b5cf6', '#6d28d9'],
  [TagCategory.Notice]: ['#8b5cf6', '#4f46e5'],
  [TagCategory.Biz]: ['#6366f1', '#4338ca'],
  [TagCategory.Alert]: ['#ef4444', '#b91c1c'],
  [TagCategory.Poll]: ['#38bdf8', '#0369a1'],
  [TagCategory.HotNow]: ['#f97316', '#dc2626'],
};

export const TAG_EMOJIS: Readonly<Record<TagCategory, string>> = {
  [TagCategory.Dating]: 'D',
  [TagCategory.Game]: 'G',
  [TagCategory.Job]: 'J',
  [TagCategory.Around]: 'A',
  [TagCategory.Shop]: '🛍️',
  [TagCategory.Help]: '🔧',
  [TagCategory.Food]: '🍜',
  [TagCategory.Service]: '🛠️',
  [TagCategory.Beauty]: '💇',
  [TagCategory.Health]: '🏥',
  [TagCategory.Fitness]: '💪',
  [TagCategory.Learn]: '📚',
  [TagCategory.Auto]: '🚗',
  [TagCategory.Space]: '🏠',
  [TagCategory.Travel]: '✈️',
  [TagCategory.Event]: '🎉',
  [TagCategory.Notice]: '📌',
  [TagCategory.Biz]: '🏢',
  [TagCategory.Alert]: '⚠️',
  [TagCategory.Poll]: '🗳️',
  [TagCategory.HotNow]: '🔥',
};
