export enum TagCategory {
  News        = 'news',
  Weather     = 'weather',
  Food        = 'food',
  Event       = 'event',
  Sale        = 'sale',
  Traffic     = 'traffic',
  Alert       = 'alert',
  Sports      = 'sports',
  Fitness     = 'fitness',
  Environment = 'environment',
  Business    = 'business',
  Tech        = 'tech',
  Art         = 'art',
  Health      = 'health',
  Market      = 'market',
  Entertainment = 'entertainment',
  Startup     = 'startup',
  Network     = 'network',
  Utility     = 'utility',
  Shopping    = 'shopping',
  Question    = 'question',
  Bulletin    = 'bulletin',
}

export const TAG_COLORS: Readonly<Record<TagCategory, [string, string]>> = {
  [TagCategory.News]:          ['#3b82f6', '#1d4ed8'],
  [TagCategory.Weather]:       ['#06b6d4', '#0284c7'],
  [TagCategory.Food]:          ['#f97316', '#c2410c'],
  [TagCategory.Event]:         ['#8b5cf6', '#6d28d9'],
  [TagCategory.Alert]:         ['#ef4444', '#b91c1c'],
  [TagCategory.Fitness]:       ['#22c55e', '#15803d'],
  [TagCategory.Shopping]:      ['#ec4899', '#be185d'],
  [TagCategory.Business]:      ['#6366f1', '#4338ca'],
  [TagCategory.Tech]:          ['#14b8a6', '#0f766e'],
  [TagCategory.Health]:        ['#84cc16', '#4d7c0f'],
  [TagCategory.Art]:           ['#f59e0b', '#b45309'],
  [TagCategory.Sports]:        ['#0ea5e9', '#0369a1'],
  [TagCategory.Environment]:   ['#10b981', '#065f46'],
  [TagCategory.Market]:        ['#f43f5e', '#be123c'],
  [TagCategory.Entertainment]: ['#a855f7', '#7e22ce'],
  [TagCategory.Startup]:       ['#6366f1', '#312e81'],
  [TagCategory.Network]:       ['#64748b', '#334155'],
  [TagCategory.Utility]:       ['#78716c', '#44403c'],
  [TagCategory.Traffic]:       ['#fb923c', '#c2410c'],
  [TagCategory.Sale]:          ['#4ade80', '#15803d'],
  [TagCategory.Question]:      ['#38bdf8', '#0369a1'],
  [TagCategory.Bulletin]:      ['#8b5cf6', '#4f46e5'],
};

export const TAG_EMOJIS: Readonly<Partial<Record<TagCategory, string>>> = {
  [TagCategory.News]:          '📰',
  [TagCategory.Weather]:       '⛅',
  [TagCategory.Food]:          '🍜',
  [TagCategory.Event]:         '🎉',
  [TagCategory.Alert]:         '⚠️',
  [TagCategory.Fitness]:       '💪',
  [TagCategory.Shopping]:      '🛍️',
  [TagCategory.Business]:      '🏢',
  [TagCategory.Tech]:          '💻',
  [TagCategory.Health]:        '🏥',
  [TagCategory.Art]:           '🎨',
  [TagCategory.Sports]:        '⚽',
  [TagCategory.Environment]:   '🌿',
  [TagCategory.Market]:        '🏪',
  [TagCategory.Entertainment]: '🎭',
  [TagCategory.Startup]:       '🚀',
  [TagCategory.Network]:       '🔗',
  [TagCategory.Utility]:       '🔧',
  [TagCategory.Traffic]:       '🚦',
  [TagCategory.Sale]:          '💰',
  [TagCategory.Bulletin]:      '📌',
};
